id: understand_design
learningObjectives:
- Understanding a Figma Design
hints:
- Open the figma link and try to understand the design.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Hiya i'm the new Product Designer, so don’t know if you were updated, but there’s a design favor I need from you. We need to update the design for one of the cards in the marketplace. Can you take a look?  Here’s the link for the [design](https://figma.com)"
        delay: 1500
      - text: "Once you’ve taken a look and understood the new design components, you need to update the current design according to what Chelsea designed in Figma."
        delay: 3500
trigger:
  type: user_message
  params:
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - don't
          - - understand
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Please Open the figma link and look at the updated design.
              delay: 1300
      if:
       conditions:
       - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - ready
          - - understood
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Great, let me know when the PR is ready.
              delay: 2500
