id: search_empty
learningObjectives:
  - Mobile responsiveness
hints:
  - Open dev tools and try to play with the CSS attributes. Try mobile view.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Oh no it's not working well on mobile!"
            delay: 1500
          - text: "Fix it please."
            delay: 3500
          - text: And as usual, when ready, open a PR.
            delay: 1200

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: keen
                message: Got it, will review in a sec’

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Got it, will review in a sec’
                    delay: 300
        github_pr_workflow_complete_success:
          do:
            - actionId: github_pr_approve
              params:
                person: keen
                message: Approved! Awesome job 😀

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Approved! Awesome job 😀 Go ahead and merge it.
                    delay: 300
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: keen
                message: Let’s try this again, shall we?

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Let’s try this again, shall we?
                    delay: 300
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  backend:
  frontend:
    capabilities:
      - jest-puppeteer
      - "puppeteer@18.1.0"
    testFile: "implement_design.test.js"