id: pixelspolice_implement_design
learningObjectives:
  - Implementing a Figma design from Scratch with React
hints:
  - Open dev tools and try to play with the CSS attributes.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Hiya I'm the new Product Designer, so don’t know if you were updated, but there’s a design favor I need from you. We need to update the design for one of the cards in the marketplace. Can you take a look?  Here’s the link for the [design](https://www.figma.com/file/FImUX4qD76LVojt2txU2Xg/Untitled?node-id=1%3A3)"
            delay: 1500
          - text: "Once you’ve taken a look and understood the new design components, you need to update the current design according to what Chelsea designed in Figma."
            delay: 1500
          - text: And as usual, when ready, open a PR.
            delay: 1200

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: keen
                message: Got it, will review in a sec’

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Got it, will review in a sec’
                    delay: 300
        github_pr_workflow_complete_success:
          do:
            - actionId: github_pr_approve
              params:
                person: keen
                message: Approved! Awesome job 😀 Go ahead and merge it.

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Approved! Awesome job 😀.
                    delay: 300
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: keen
                message: The check on the PR failed, can you investigate what happened and try again?

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: The check on the PR failed, can you investiagte what happened and try again?
                    delay: 300
        github_pr_merged:
          do:
            - actionId: finish_step

githubActions:
  backend:
  frontend:
    capabilities:
      - jest-puppeteer
      - "puppeteer@18.1.0"
    testFile: "implement_design.test.js"
