id: mobile_responsiveness
learningObjectives:
  - Mobile responsiveness
hints:
  - Open dev tools and try to play with the CSS attributes. Try mobile view.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: keen
        messages:
          - text: "Oh snap it's not working well on mobile"
            delay: 1500
          - text: "can you please take a look?"
            delay: 1500
          - text: Don't forget to open a PR so that I'll know when you are done.
            delay: 1200

trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch:
      key: ${eventType}
      cases:
        github_pr_opened:
          do:
            - actionId: github_pr_comment
              params:
                person: keen
                message: Got it, will review in a sec’

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Got it, will review in a sec’
                    delay: 300
        github_pr_workflow_complete_success:
          do:
            - actionId: github_pr_approve
              params:
                person: keen
                message: Approved! Awesome job 😀 Go ahead and merge it.

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: Oh wow, it looks great 😀.
                    delay: 300
        github_pr_workflow_complete_failure:
          do:
            - actionId: github_pr_reject
              params:
                person: keen
                message: The check on the PR failed, can you investigate what happened and try again?

            - actionId: bot_message
              params:
                person: keen
                messages:
                  - text: The check on the PR failed, can you investiagte what happened and try again?
                    delay: 300
        github_pr_merged:
          do:
            - actionId: bot_message
              params:
                person:
                messages:
                  - text: Nice job, thank you for helping out
                    delay: 2000
            - actionId: finish_step

githubActions:
  backend:
  frontend:
    capabilities:
      - jest-puppeteer
      - "puppeteer@18.1.0"
    testFile: "responsiveness.test.js"
